safe:        false
auto:        true
server:      true
server_port: 4000
baseurl:    /
url: http://localhost:4000
exclude: [ post ]

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /articles/:title

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

